/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/users/me/password": {
    put: operations["updatePassword"];
  };
  "/api/v1/trips/{tripId}/stops": {
    put: operations["updateTripStops"];
    patch: operations["addStop"];
  };
  "/api/v1/trips/{id}": {
    get: operations["getTrip"];
    put: operations["updateTrip"];
    delete: operations["deleteTrip"];
  };
  "/api/v1/profile/me": {
    get: operations["getMyProfile"];
    put: operations["updateProfile"];
  };
  "/api/v1/parcels/{id}": {
    get: operations["getParcel"];
    put: operations["updateParcel"];
    delete: operations["deleteParcel"];
  };
  "/api/v1/users/verification/verify": {
    post: operations["verify"];
  };
  "/api/v1/users/verification/request": {
    post: operations["requestVerification"];
  };
  "/api/v1/users/register": {
    post: operations["register"];
  };
  "/api/v1/users/password/reset": {
    post: operations["resetPassword"];
  };
  "/api/v1/users/password/reset/request": {
    post: operations["requestPasswordReset"];
  };
  "/api/v1/trips": {
    get: operations["getAllTrips"];
    post: operations["createTrip"];
  };
  "/api/v1/reviews": {
    get: operations["getUserReviews"];
    post: operations["create"];
  };
  "/api/v1/payments/webhook/stripe": {
    post: operations["handleWebhook"];
  };
  "/api/v1/payments/bookings/{bookingId}/checkout": {
    post: operations["createCheckoutSession"];
  };
  "/api/v1/parcels": {
    get: operations["getParcels"];
    post: operations["createParcel"];
  };
  "/api/v1/images/presign": {
    post: operations["getPresignUrl"];
  };
  "/api/v1/images/confirm": {
    post: operations["confirmUpload"];
  };
  "/api/v1/geocoding/geocode": {
    post: operations["geocode"];
  };
  "/api/v1/conversations/with/{otherUserId}": {
    post: operations["getOrCreateConversation"];
  };
  "/api/v1/bookings": {
    post: operations["create_1"];
  };
  "/api/v1/auth/refresh": {
    post: operations["refresh"];
  };
  "/api/v1/auth/logout": {
    post: operations["logout"];
  };
  "/api/v1/auth/login": {
    post: operations["login"];
  };
  "/api/v1/notifications/{id}/read": {
    patch: operations["markAsRead"];
  };
  "/api/v1/conversations/{conversationId}/read": {
    patch: operations["markAsRead_1"];
  };
  "/api/v1/bookings/{bookingId}/reject": {
    patch: operations["rejectBooking"];
  };
  "/api/v1/bookings/{bookingId}/confirm-pickup": {
    patch: operations["confirmPickUp"];
  };
  "/api/v1/bookings/{bookingId}/complete": {
    patch: operations["complete"];
  };
  "/api/v1/bookings/{bookingId}/cancel": {
    patch: operations["cancel"];
  };
  "/api/v1/bookings/{bookingId}/accept": {
    patch: operations["acceptBooking"];
  };
  "/api/v1/users": {
    get: operations["getAllUsers"];
  };
  "/api/v1/users/{id}": {
    get: operations["getUserById"];
  };
  "/api/v1/users/me": {
    get: operations["getMe"];
    delete: operations["deleteMe"];
  };
  "/api/v1/trips/{tripId}/bookings": {
    get: operations["getTripBookings"];
  };
  "/api/v1/trips/me": {
    get: operations["getMyTrips"];
  };
  "/api/v1/reviews/me": {
    get: operations["getReviewsMe"];
  };
  "/api/v1/profile/{profileId}": {
    get: operations["getProfileById"];
  };
  "/api/v1/parcels/{parcelId}/tracking": {
    get: operations["getTrackingEvents"];
  };
  "/api/v1/parcels/{parcelId}/bookings": {
    get: operations["getParcelBookings"];
  };
  "/api/v1/parcels/me": {
    get: operations["getMyParcels"];
  };
  "/api/v1/notifications": {
    get: operations["getMyNotifications"];
  };
  "/api/v1/notifications/{notifId}": {
    get: operations["getNotificationByID"];
  };
  "/api/v1/match": {
    get: operations["getMatchingTrips"];
  };
  "/api/v1/conversations": {
    get: operations["getMyConversations"];
  };
  "/api/v1/conversations/{conversationId}": {
    get: operations["getConversationDetails"];
  };
  "/api/v1/conversations/{conversationId}/unread-count": {
    get: operations["getUnreadCount"];
  };
  "/api/v1/bookings/{bookingId}": {
    get: operations["getBooking"];
  };
  "/api/v1/trips/{tripId}/stops/{stopId}": {
    delete: operations["deleteTripStop"];
  };
  "/api/v1/reviews/{id}": {
    delete: operations["remove"];
  };
  "/api/v1/notifications/{id}": {
    delete: operations["delete"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    UpdatePasswordRequest: {
      currentPassword: string;
      newPassword: string;
    };
    AddressRequest: {
      street: string;
      city: string;
      postalCode: string;
      country: string;
    };
    TripStopRequest: {
      /** Format: int32 */
      order: number;
      address: components["schemas"]["AddressRequest"];
    };
    Address: {
      street?: string;
      city?: string;
      postalCode?: string;
      country?: string;
      /** Format: double */
      latitude?: number;
      /** Format: double */
      longitude?: number;
    };
    TripStopDto: {
      /** Format: uuid */
      id?: string;
      /** Format: int32 */
      order?: number;
      address?: components["schemas"]["Address"];
    };
    Price: {
      /** Format: int64 */
      amountInCents?: number;
      currency: string;
    };
    TripUpdateRequest: {
      departureAddress?: components["schemas"]["AddressRequest"];
      arrivalAddress?: components["schemas"]["AddressRequest"];
      /** Format: date */
      departureDate: string;
      /** Format: date */
      arrivalDate: string;
      availableWeightKg: number;
      pricePerKg: components["schemas"]["Price"];
      instantBooking: boolean;
      maxDetourKm: number;
      notes: string;
    };
    TripDetails: {
      /** Format: uuid */
      tripId?: string;
      departureAddress?: components["schemas"]["Address"];
      arrivalAddress?: components["schemas"]["Address"];
      /** Format: date */
      departureDate?: string;
      /** Format: date */
      arrivalDate?: string;
      availableWeightKg?: number;
      remainingWeightKg?: number;
      pricePerKg?: components["schemas"]["Price"];
      instantBooking?: boolean;
      maxDetourKm?: number;
      /** @enum {string} */
      state?: "PUBLISHED" | "FULL" | "IN_TRANSIT" | "COMPLETED" | "CANCELLED";
      notes?: string;
      stops?: components["schemas"]["TripStopDto"][];
      /** Format: int64 */
      bookingsCount?: number;
      /** Format: date-time */
      publishedAt?: string;
    };
    ProfileUpdateRequest: {
      firstName: string;
      lastName: string;
      phone: string;
      country: string;
      /** Format: uuid */
      avatarId?: string;
    };
    ImageDto: {
      /** Format: uuid */
      id?: string;
      url?: string;
      content?: string;
      /** Format: date-time */
      uploadedAt?: string;
    };
    ProfileSummary: {
      /** Format: uuid */
      profileId?: string;
      firstName?: string;
      lastName?: string;
      phone?: string;
      country?: string;
      avatar?: components["schemas"]["ImageDto"];
    };
    ParcelUpdateRequest: {
      description: string;
      weightKg: number;
      /** @enum {string} */
      size: "S" | "M" | "L" | "XL" | "XXL";
      fragile: boolean;
      pickupAddress?: components["schemas"]["AddressRequest"];
      dropoffAddress?: components["schemas"]["AddressRequest"];
      imageIds: string[];
      /** Format: uuid */
      thumbnailId?: string;
    };
    ParcelDetails: {
      /** Format: uuid */
      parcelId?: string;
      description?: string;
      weightKg?: number;
      /** @enum {string} */
      size?: "S" | "M" | "L" | "XL" | "XXL";
      fragile?: boolean;
      pickupAddress?: components["schemas"]["Address"];
      dropoffAddress?: components["schemas"]["Address"];
      /** @enum {string} */
      state?: "PUBLISHED" | "BOOKED" | "PICKED_UP" | "IN_TRANSIT" | "DELIVERED" | "CANCELLED";
      thumbnail?: components["schemas"]["ImageDto"];
      images?: components["schemas"]["ImageDto"][];
      /** Format: int64 */
      bookingsCount?: number;
      /** Format: date-time */
      publishedAt?: string;
    };
    VerifyEmailRequest: {
      token?: string;
    };
    RequestEmailVerification: {
      email: string;
    };
    UserCreateRequest: {
      /** Format: email */
      email: string;
      password: string;
      firstName: string;
      lastName: string;
    };
    UserDetails: {
      /** Format: uuid */
      userId?: string;
      email?: string;
      /** @enum {string} */
      role?: "USER" | "ADMIN";
      verified?: boolean;
      profile?: components["schemas"]["ProfileSummary"];
      /** Format: date-time */
      registeredAt?: string;
    };
    ResetPasswordRequest: {
      token: string;
      newPassword: string;
    };
    RequestPasswordReset: {
      /** Format: email */
      email: string;
    };
    TripCreateRequest: {
      departureAddress: components["schemas"]["AddressRequest"];
      arrivalAddress: components["schemas"]["AddressRequest"];
      /** Format: date */
      departureDate: string;
      /** Format: date */
      arrivalDate: string;
      availableWeightKg?: number;
      pricePerKg: components["schemas"]["Price"];
      instantBooking: boolean;
      maxDetourKm: number;
      notes?: string;
    };
    CreateReviewRequest: {
      /** Format: uuid */
      bookingId: string;
      /** Format: int32 */
      rating: number;
      comment?: string;
    };
    ReviewDto: {
      /** Format: uuid */
      id?: string;
      reviewer?: components["schemas"]["UserBrief"];
      /** Format: int32 */
      rating?: number;
      comment?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    UserBrief: {
      /** Format: uuid */
      userId?: string;
      firstName?: string;
      lastName?: string;
      avgRating?: number;
      /** Format: int32 */
      reviewCount?: number;
      avatar?: components["schemas"]["ImageDto"];
      verified?: boolean;
    };
    PaymentResponse: {
      /** Format: uuid */
      paymentId?: string;
      /** Format: uuid */
      bookingId?: string;
      amount?: components["schemas"]["Price"];
      /** @enum {string} */
      status?: "PENDING" | "AUTHORIZED" | "SUCCEEDED" | "FAILED" | "CANCELED" | "REFUNDED";
      clientSecret?: string;
    };
    ParcelCreateRequest: {
      description?: string;
      weightKg: number;
      /** @enum {string} */
      size: "S" | "M" | "L" | "XL" | "XXL";
      fragile?: boolean;
      pickupAddress: components["schemas"]["AddressRequest"];
      dropoffAddress: components["schemas"]["AddressRequest"];
      imageIds: string[];
      /** Format: uuid */
      thumbnailId?: string;
    };
    PresignedUrl: {
      url?: string;
      key?: string;
      /** Format: date-time */
      expiresAt?: string;
    };
    ConversationDetails: {
      /** Format: uuid */
      conversationId?: string;
      participants?: components["schemas"]["UserBrief"][];
      messages?: components["schemas"]["MessageSummary"][];
      /** Format: date-time */
      createdAt?: string;
    };
    MessageSummary: {
      /** Format: uuid */
      messageId?: string;
      sender?: components["schemas"]["UserBrief"];
      content?: string;
      images?: components["schemas"]["ImageDto"][];
      /** Format: date-time */
      sentAt?: string;
    };
    CreateBookingRequest: {
      /** Format: uuid */
      tripId: string;
      /** Format: uuid */
      parcelId: string;
    };
    BookingDto: {
      /** Format: uuid */
      bookingId?: string;
      trip?: components["schemas"]["TripSummary"];
      parcel?: components["schemas"]["ParcelSummary"];
      sender?: components["schemas"]["UserBrief"];
      carrier?: components["schemas"]["UserBrief"];
      price?: components["schemas"]["Price"];
      /** @enum {string} */
      state?: "PENDING" | "WAITING_FOR_ANSWER" | "ACCEPTED" | "REJECTED" | "CANCELLED" | "COMPLETED";
      pickupDetourKm?: number;
      dropOffDetourKm?: number;
      rejectionReason?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      respondedAt?: string;
      /** Format: date-time */
      completedAt?: string;
      /** Format: date-time */
      cancelledAt?: string;
    };
    ParcelSummary: {
      /** Format: uuid */
      parcelId?: string;
      weightKg?: number;
      /** @enum {string} */
      size?: "S" | "M" | "L" | "XL" | "XXL";
      fragile?: boolean;
      pickupCity?: string;
      dropoffCity?: string;
      /** @enum {string} */
      state?: "PUBLISHED" | "BOOKED" | "PICKED_UP" | "IN_TRANSIT" | "DELIVERED" | "CANCELLED";
      thumbnail?: components["schemas"]["ImageDto"];
      /** Format: date-time */
      publishedAt?: string;
    };
    TripSummary: {
      /** Format: uuid */
      tripId?: string;
      departureCity?: string;
      arrivalCity?: string;
      /** Format: date */
      departureDate?: string;
      /** Format: date */
      arrivalDate?: string;
      availableWeightKg?: number;
      remainingWeightKg?: number;
      pricePerKg?: components["schemas"]["Price"];
      instantBooking?: boolean;
      /** @enum {string} */
      state?: "PUBLISHED" | "FULL" | "IN_TRANSIT" | "COMPLETED" | "CANCELLED";
      /** Format: int32 */
      stopCount?: number;
      /** Format: date-time */
      publishedAt?: string;
    };
    AuthRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    UserSummary: {
      /** Format: uuid */
      userId?: string;
      email?: string;
      /** @enum {string} */
      role?: "USER" | "ADMIN";
      verified?: boolean;
      /** Format: date-time */
      registeredAt?: string;
    };
    TripBookingDto: {
      /** Format: uuid */
      bookingId?: string;
      parcel?: components["schemas"]["ParcelSummary"];
      sender?: components["schemas"]["UserBrief"];
      price?: components["schemas"]["Price"];
      /** @enum {string} */
      state?: "PENDING" | "WAITING_FOR_ANSWER" | "ACCEPTED" | "REJECTED" | "CANCELLED" | "COMPLETED";
      pickupDetourKm?: number;
      dropOffDetourKm?: number;
      rejectionReason?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      respondedAt?: string;
      /** Format: date-time */
      completedAt?: string;
      /** Format: date-time */
      cancelledAt?: string;
    };
    ProfileDetails: {
      /** Format: uuid */
      profileId?: string;
      firstName?: string;
      lastName?: string;
      phone?: string;
      country?: string;
      avgRating?: number;
      /** Format: int32 */
      reviewCount?: number;
      /** Format: int32 */
      completedTrips?: number;
      /** Format: int32 */
      deliveredParcels?: number;
      reviews?: components["schemas"]["ReviewDto"][];
      avatar?: components["schemas"]["ImageDto"];
    };
    TrackEventDto: {
      /** Format: uuid */
      id?: string;
      /** @enum {string} */
      state?: "PUBLISHED" | "BOOKED" | "PICKED_UP" | "IN_TRANSIT" | "DELIVERED" | "CANCELLED";
      note?: string;
      /** Format: date-time */
      occurredAt?: string;
    };
    ParcelBookingDto: {
      /** Format: uuid */
      bookingId?: string;
      trip?: components["schemas"]["TripSummary"];
      carrier?: components["schemas"]["UserBrief"];
      price?: components["schemas"]["Price"];
      /** @enum {string} */
      state?: "PENDING" | "WAITING_FOR_ANSWER" | "ACCEPTED" | "REJECTED" | "CANCELLED" | "COMPLETED";
      pickupDetourKm?: number;
      dropOffDetourKm?: number;
      rejectionReason?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      respondedAt?: string;
      /** Format: date-time */
      completedAt?: string;
      /** Format: date-time */
      cancelledAt?: string;
    };
    NotificationDto: {
      /** Format: uuid */
      notificationId?: string;
      /** @enum {string} */
      type?: "VERIFY_USER" | "RESET_PASSWORD" | "USER_CREATED" | "MESSAGE_RECEIVED" | "REQUEST_RECEIVED" | "BOOKING_CREATED" | "BOOKING_CANCELED" | "BOOKING_COMPLETED" | "BOOKING_PAID" | "TRIP_CANCELLED" | "PARCEL_DELIVERED";
      /** Format: uuid */
      referenceId?: string;
      isRead?: boolean;
      payload?: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      createdAt?: string;
    };
    MatchResultDto: {
      trip?: components["schemas"]["TripSummary"];
      owner?: components["schemas"]["UserBrief"];
      price?: components["schemas"]["Price"];
      /** Format: double */
      score?: number;
    };
    ConversationSummary: {
      /** Format: uuid */
      conversationId?: string;
      participants?: components["schemas"]["UserBrief"][];
      lastMessage?: components["schemas"]["MessageSummary"];
      /** Format: date-time */
      createdAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  updatePassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePasswordRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  updateTripStops: {
    parameters: {
      path: {
        tripId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TripStopRequest"][];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["TripStopDto"][];
        };
      };
    };
  };
  addStop: {
    parameters: {
      path: {
        tripId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddressRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  getTrip: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["TripDetails"];
        };
      };
    };
  };
  updateTrip: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TripUpdateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["TripDetails"];
        };
      };
    };
  };
  deleteTrip: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  getMyProfile: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProfileDetails"];
        };
      };
    };
  };
  updateProfile: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfileUpdateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProfileSummary"];
        };
      };
    };
  };
  getParcel: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ParcelDetails"];
        };
      };
    };
  };
  updateParcel: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ParcelUpdateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ParcelDetails"];
        };
      };
    };
  };
  deleteParcel: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  verify: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyEmailRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  requestVerification: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RequestEmailVerification"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserDetails"];
        };
      };
    };
  };
  resetPassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  requestPasswordReset: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RequestPasswordReset"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  getAllTrips: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["TripSummary"][];
        };
      };
    };
  };
  createTrip: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TripCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["TripDetails"];
        };
      };
    };
  };
  getUserReviews: {
    parameters: {
      query: {
        revieweeId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ReviewDto"][];
        };
      };
    };
  };
  create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateReviewRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ReviewDto"];
        };
      };
    };
  };
  handleWebhook: {
    requestBody: {
      content: {
        "application/json": string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  createCheckoutSession: {
    parameters: {
      path: {
        bookingId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PaymentResponse"];
        };
      };
    };
  };
  getParcels: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ParcelSummary"][];
        };
      };
    };
  };
  createParcel: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ParcelCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ParcelDetails"];
        };
      };
    };
  };
  getPresignUrl: {
    parameters: {
      query: {
        content: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PresignedUrl"];
        };
      };
    };
  };
  confirmUpload: {
    parameters: {
      query: {
        key: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ImageDto"];
        };
      };
    };
  };
  geocode: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddressRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Address"];
        };
      };
    };
  };
  getOrCreateConversation: {
    parameters: {
      path: {
        otherUserId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ConversationDetails"];
        };
      };
    };
  };
  create_1: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBookingRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["BookingDto"];
        };
      };
    };
  };
  refresh: {
    parameters: {
      cookie?: {
        REFRESH_TOKEN?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserDetails"];
        };
      };
    };
  };
  logout: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserDetails"];
        };
      };
    };
  };
  markAsRead: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  markAsRead_1: {
    parameters: {
      path: {
        conversationId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": number;
        };
      };
    };
  };
  rejectBooking: {
    parameters: {
      query: {
        reason: string;
      };
      path: {
        bookingId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  confirmPickUp: {
    parameters: {
      query: {
        code: string;
      };
      path: {
        bookingId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  complete: {
    parameters: {
      query: {
        code: string;
      };
      path: {
        bookingId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  cancel: {
    parameters: {
      query?: {
        reason?: string;
      };
      path: {
        bookingId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  acceptBooking: {
    parameters: {
      path: {
        bookingId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  getAllUsers: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserSummary"][];
        };
      };
    };
  };
  getUserById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserDetails"];
        };
      };
    };
  };
  getMe: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserDetails"];
        };
      };
    };
  };
  deleteMe: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  getTripBookings: {
    parameters: {
      path: {
        tripId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["TripBookingDto"][];
        };
      };
    };
  };
  getMyTrips: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["TripSummary"][];
        };
      };
    };
  };
  getReviewsMe: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ReviewDto"][];
        };
      };
    };
  };
  getProfileById: {
    parameters: {
      path: {
        profileId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProfileDetails"];
        };
      };
    };
  };
  getTrackingEvents: {
    parameters: {
      path: {
        parcelId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrackEventDto"][];
        };
      };
    };
  };
  getParcelBookings: {
    parameters: {
      path: {
        parcelId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ParcelBookingDto"][];
        };
      };
    };
  };
  getMyParcels: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ParcelSummary"][];
        };
      };
    };
  };
  getMyNotifications: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["NotificationDto"][];
        };
      };
    };
  };
  getNotificationByID: {
    parameters: {
      path: {
        notifId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["NotificationDto"];
        };
      };
    };
  };
  getMatchingTrips: {
    parameters: {
      query: {
        parcelId: string;
        date: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["MatchResultDto"][];
        };
      };
    };
  };
  getMyConversations: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ConversationSummary"][];
        };
      };
    };
  };
  getConversationDetails: {
    parameters: {
      path: {
        conversationId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ConversationDetails"];
        };
      };
    };
  };
  getUnreadCount: {
    parameters: {
      path: {
        conversationId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": number;
        };
      };
    };
  };
  getBooking: {
    parameters: {
      path: {
        bookingId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["BookingDto"];
        };
      };
    };
  };
  deleteTripStop: {
    parameters: {
      path: {
        tripId: string;
        stopId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
}
